import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const platform = localFont({
  src: [
    {
      path: "../public/fonts/platform/Platform-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/platform/Platform-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/platform/Platform-Bold.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-platform",
});

const figtree = Figtree({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "CCNPlatform",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${platform.variable} ${figtree.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
